// 1. Carrega as variaveis do arquivo .env para process.env.
//    Elas contem os dados necessarios para acessar o PostgreSQL.
import 'dotenv/config';
import pg from 'pg';

const { Pool } = pg;

// 2. Monta a configuracao da conexao.
//    DATABASE_URL e comum em servicos hospedados, como o Neon.
//    Se ela nao existir, usamos as variaveis separadas PG* ou DB_*.
const poolConfig = process.env.DATABASE_URL
	? { connectionString: process.env.DATABASE_URL }
	: {
		host: process.env.PGHOST || process.env.DB_HOST,
		port: Number(process.env.PGPORT || process.env.DB_PORT || 5432),
		database: process.env.PGDATABASE || process.env.DB_NAME,
		user: process.env.PGUSER || process.env.DB_USER,
		password: process.env.PGPASSWORD || process.env.DB_PASSWORD,
	};

// 3. Alguns provedores exigem uma conexao criptografada por SSL.
//    rejectUnauthorized: false permite o certificado usado pelo provedor.
if (process.env.DATABASE_SSL === 'true' || process.env.PGSSL === 'true') {
	poolConfig.ssl = { rejectUnauthorized: false };
}

// 4. O Pool gerencia e reutiliza varias conexoes com o banco.
//    Assim, a aplicacao nao precisa abrir uma nova conexao a cada consulta.
export const pool = new Pool(poolConfig);

let databaseReady;

// 5. Cria as tabelas automaticamente na primeira consulta.
//    IF NOT EXISTS evita erro quando as tabelas ja foram criadas anteriormente.
export function initializeDatabase() {
	if (!databaseReady) {
		databaseReady = pool.query(`
			-- Tabela de usuarios cadastrados no sistema.
			CREATE TABLE IF NOT EXISTS users (
				id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				nome TEXT NOT NULL,
				email TEXT NOT NULL UNIQUE,
				senha TEXT NOT NULL,
				status TEXT NOT NULL DEFAULT 'pendente_confirmacao',
				"confirmationToken" TEXT,
				"confirmationExpiresAt" TIMESTAMPTZ,
				cpf TEXT,
				nascimento TEXT,
				telefone TEXT,
				"createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
			);

			-- Tabela de relatos enviados pelos usuarios.
			-- userId relaciona cada relato ao seu autor.
			CREATE TABLE IF NOT EXISTS reports (
				id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				"userId" INTEGER REFERENCES users(id) ON DELETE SET NULL,
				categoria TEXT NOT NULL,
				tipo TEXT,
				endereco TEXT,
				descricao TEXT,
				status TEXT NOT NULL DEFAULT 'pendente',
				protocolo TEXT UNIQUE,
				"criadoEm" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
				latitude DOUBLE PRECISION,
				longitude DOUBLE PRECISION
			);
		`).catch((error) => {
			databaseReady = undefined;
			throw error;
		});
	}

	return databaseReady;
}

// 6. Todas as operacoes dos repositorios passam por esta funcao.
//    Primeiro garantimos que o banco esteja preparado e depois executamos
//    o SQL com seus parametros. Os parametros ($1, $2...) evitam SQL Injection.
export async function query(text, params) {
	await initializeDatabase();
	return pool.query(text, params);
}
